### ISSUE TITLE
Paired PSCBS - Error running call NTCN

### ISSUE THREAD

**Issue by gaiusjaugustus** [HenrikBengtsson/PSCBS#34]
I am running my samples through Paired PSCBS, and using callLOH and callNTCN to identify regions of copy neutral LOH in ~300 samples.

For the first few samples, everything went smoothly.  However, so far, one of the samples has given me this error after running callNTCN.

Error: Less that two modes were found in the empirical density of C1 after removing 7 modes that are too weak (density < 0.2): 1 

Here is a gist of the code I'm using, the error, and the traceback:
https://gist.github.com/gaiusjaugustus/c63a826bc6935b505059f2e2b0a4e437

And here is an image output of the sample:
![tcga-5m-aat6_tumor_blackvstcga-5m-aat6_normal_black chr1-25 pairedpscbs](https://cloud.githubusercontent.com/assets/10555763/16016744/56084826-3151-11e6-90c4-60d0687259ed.png)

**##Can you please help me understand the error and is there another way to call copy number neutral regions on these samples?**

Thank you,
Gaius

**Comment by HenrikBengtsson** [comment]
Sorry, busy time and then I forgot about this one.  It's been a year since you've asked, but I'll still answer here in case it helps our someone else finding this later.

As the Paired PSCBS vignettes says, `callNTCN()` is a method "under development".  This is still true and since we're extremely conservative when we claim a method to be done (we want you to be able to trust our methods), this is likely to be the case for quite a while until we had time to do more research development on it.  Having said that, as the vignette suggests,
```r
fit <- callNTCN(fit)
```
is equivalent to:
```r
kappa <- estimateKappa(fit)
deltaCN <- estimateDeltaCN(fit, scale = 1, kappa = kappa)
fit <- callNTCN(fit, delta = deltaCN)
```

The error your observing:

> Error: Less that two modes were found in the empirical density of C1 after removing 7 modes that are too weak (density < 0.2): 1

comes from the `estimateKappa(fit)` step (this can be seen from the `traceback()` output).  Estimating kappa is tricky (see vignette for what it tries to do) and to fully automate for type of samples is complicated - the problem becomes harder and harder the less copy-number aberrations there are in the tumor.

The `estimateKappa()` S3 method lacks documentation, but if you follow the code, `estimateKappa` -> `estimateKappa.PairedPSCBS` -> `estimateKappaByC1Density` -> `estimateKappaByC1Density.PairedPSCBS`, we can see the there are the following parameters (arguments) to play with:
```r
> args(estimateKappaByC1Density.PairedPSCBS)
function (this, typeOfWeights = c("dhNbrOfLoci", "sqrt(dhNbrOfLoci)"), 
    adjust = 1, from = 0, minDensity = 0.2, ..., verbose = FALSE) 
NULL
```
More precisely, one can play with `adjust` and `minDensity`.  For instance, my using smoothing parameter `adjust = 0.5` (passed to `stats::density()`) it will be more sensitive to small changes and by using say `minDensity = 0.1` (a calling threshold) one might be able to pick up small changes as well.  That's all I can suggest - you can peek at the code of that method to see what it does.

(I'm going to close this issue with the above, because it's likely that it's obsolete by now. Feel free to reopen if still of interest)
